name: ucommunicate
favicon: null
layout_spectrum: 0.40719
typography_spectrum: 0.02688504
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Uncommon Communication
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#424242'
    - '#e1e1e1'
    - '#6e6e6e'
    - '#b5b5b5'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.292133
purpose: []
