collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.02688504
color:
  saturation: 0.5531352
  brandStrength: 0.6342642
  lightness: 0.03581979
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  rhythmicContrast: 0.292133
layout_spectrum: 0.4693019
name: ucommunicate
