name: ucommunicate
favicon: null
layout_spectrum: 0.40719
typography_spectrum: 0.02688504
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Uncommon Communication
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070c10'
    - '#bdc3bf'
    - '#fc7500'
    - '#fcb33a'
    - '#fefdfe'
  brandStrength: 0.6342642
  lightness: 0.03581979
  saturation: 0
  rhythmicContrast: 0.292133
purpose: []
